server.port: 9820
spring:
  data: 
      mongodb: 
             uri: mongodb://172.20.11.85:27017,172.20.11.86:27017/order-stock-message-service
  rabbitmq: 
           host: 172.20.10.61
           port: 5672
           username: scm-message-service
           password: scm-message-service
           virtual-host: /scm-message-service
  cloud: 
        stream: 
              bindings: 
                        orders: 
                              destination: SupplierOrderSync
                              content-type: application/json
              rabbit: 
                      bindings: 
                        orders: 
                              producer: 
                                       prefix: HA.
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image: 
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).