feign.hystrix.enabled: false
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
spring: 
  rabbitmq: 
           host: 172.20.11.50
           port: 5672
           username: ephub-message-service
           password: ephub-message-service
           virtual-host: /ephub-message-service
  cloud:
        consul: 
          host: localhost
          port: 8500
          discovery: 
            prefer-agent-address: true
            prefer-ip-address: true
            health-check-interval: 10s
            health-check-timeout: 10s            
            register: true
            register-health-check: true
        stream: 
              bindings: 
                        pendingProductImportTask: 
                              destination: pending.product.import.task
                              content-type: application/json
                        hubProductImportTask: 
                              destination: hub.product.import.task
                              content-type: application/json
                        productExportTask: 
                              destination: product.export.task
                              content-type: application/json
              rabbit: 
                      bindings: 
                            pendingProductImportTask: 
                                  producer: 
                                           prefix: HA.
                            hubProductImportTask: 
                                  producer: 
                                           prefix: HA.
                            productExportTask: 
                                  producer: 
                                           prefix: HA.
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8
  ftp:
       host: 172.20.10.88
       port: 21
       userName: ftpuser2
       password: shangpin@123
       ftpHubPath: /hub/
       ftpPendingPath: /pending/
  #mail: 
       #default-recipient: yan_xiao_bin@126.com
       #default-sender: yanxiaobin@shangpin.com
       #default-encoding: UTF-8 # Default MimeMessage encoding.
       #host: smtp.263.net # SMTP server host. For instance `smtp.example.com`
       #port: 25 # SMTP server port.
       #protocol: smtp # Protocol used by the SMTP server.
       #username: yanxiaobin@shangpin.com # Login user of the SMTP server.
       #password: 123.com # Login password of the SMTP server.
       #test-connection: false # Test that the mail server is available on startup.
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).
shangpin:
   hub:
       callAddress:
             gmsAddProductUrl: http://scmapi.spidc1.com/gms/Product/AddProduct
             gmsSizeUrl: http://scmapi.spidc1.com/gms/ProductBasicData/GetProductSize
             gmsBrandUrl: http://scmapi.spidc1.com/gms/ProductBasicData/GetBrands
             gmsCategoryUrl: http://scmapi.spidc1.com/gms/ProductBasicData/GetCategory
             scmsSupplierInfoUrl: http://scm.shangpin.com/scms/Supplier/GetSupplierInfoListByNo?supplierNo=
             sopSkuListBySupplierSkuNoUrl: http://sopoutapi.spidc1.com/Product/GetSopSkuListBySupplierSkuNo