feign.hystrix.enabled: false
spring: 
  rabbitmq: 
           host: 192.168.20.175
           port: 5672
           username: ephub-message-service-qa
           password: ephub-message-service-qa
           virtual-host: /ephub-message-service-qa
  cloud:
        consul: 
          host: localhost
          port: 8500
          discovery: 
            prefer-agent-address: true
            prefer-ip-address: true
            health-check-interval: 15s
            health-check-timeout: 15s            
            register: true
            register-health-check: true
        stream: 
              bindings: 
                        pendingProductImportTask: 
                              destination: pending.product.import.task
                              content-type: application/json
                        hubProductImportTask: 
                              destination: hub.product.import.task
                              content-type: application/json
              rabbit: 
                      bindings: 
                            pendingProductImportTask: 
                                  producer: 
                                           prefix: HA.
                            hubProductImportTask: 
                                  producer: 
                                           prefix: HA.
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
  ftp:
       host: 192.168.20.110
       port: 21
       userName: dev
       password: shangpin@123
       ftpHubPath: hub/
       ftpPendingPath: pending/
  mail: 
       default-recipient: yan_xiao_bin@126.com
       default-sender: yanxiaobin@shangpin.com
       default-encoding: UTF-8 # Default MimeMessage encoding.
       host: smtp.263.net # SMTP server host. For instance `smtp.example.com`
       port: 25 # SMTP server port.
       protocol: smtp # Protocol used by the SMTP server.
       username: yanxiaobin@shangpin.com # Login user of the SMTP server.
       password: 123.com # Login password of the SMTP server.
       test-connection: false # Test that the mail server is available on startup.
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).
shangpin:
   hub:
       callAddress:
             gmsAddProductUrl: http://qa.scmapi.shangpin.com/gms/Product/AddProduct
             gmsSizeUrl: http://qa.scmapi.shangpin.com/gms/GetProductSize
             gmsBrandUrl: http://qa.scmapi.shangpin.com/gms/GetBrands
             gmsCategoryUrl: http://qa.scmapi.shangpin.com/gms/GetCategory