feign.hystrix.enabled: false
spring: 
  rabbitmq: 
           host: 192.168.20.175
           port: 5672
           username: scm-message-service-qa
           password: scm-message-service-qa
           virtual-host: /scm-message-service-qa
  cloud: 
        consul: 
          host: localhost
          port: 8500
          discovery: 
            prefer-agent-address: true
            prefer-ip-address: true
            health-check-interval: 10s
            register: false
            register-health-check: false
        stream: 
              bindings: 
                        supplierPictureProduct: 
                              destination: supplier.product.picture
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
              rabbit: 
                      bindings: 
                            supplierPictureProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
  mail: 
       default-recipient: yan_xiao_bin@126.com
       default-sender: yanxiaobin@shangpin.com
       default-encoding: UTF-8 # Default MimeMessage encoding.
       host: smtp.263.net # SMTP server host. For instance `smtp.example.com`
       port: 25 # SMTP server port.
       protocol: smtp # Protocol used by the SMTP server.
       username: yanxiaobin@shangpin.com # Login user of the SMTP server.
       password: 123.com # Login password of the SMTP server.
       test-connection: false # Test that the mail server is available on startup.
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).